config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :emptemperatures do 
    get '/emptemperatures.xls', to: 'emptemperatures#export_xlxs_employe_temperature', as: 'export', on: :collection
  end
  resources :temperatures do
   get '/temperatures.xls', to: 'temperatures#export_xlxs', as: 'export' , on: :collection
  end
  resources :languages do
      get '/change_language', to: 'languages#change_language', as: 'change_language', on: :collection

      get '/current_language', to: 'languages#current_language', as: 'c_language', on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/emptemperature.rb
class Emptemperature < ApplicationRecord
end

app/controllers/emptemperatures_controller.rb
class EmptemperaturesController < ApplicationController
  before_action :set_emptemperature, only: [:show, :edit, :update, :destroy]

  # GET /emptemperatures
  # GET /emptemperatures.json
  def index
    @emptemperatures = Emptemperature.all
    respond_to do |format|
      format.html
      format.json {render json: EmptemperatureDatatable.new(params,{ show: emptemperature_path('_')})}
    end
  end

  # GET /emptemperatures/1
  # GET /emptemperatures/1.json
  def show
     @current_symptoms = JSON.parse(@emptemperature.symptoms)
  end

  # GET /emptemperatures/new
  def new
    @emptemperature = Emptemperature.new
  end

  # GET /emptemperatures/1/edit
  def edit
    @current_symptoms = JSON.parse(@emptemperature.symptoms)
  end

  # POST /emptemperatures
  # POST /emptemperatures.json
  def create
    @emptemperature = Emptemperature.new(emptemperature_params)

    respond_to do |format|
      if @emptemperature.save
        format.html { redirect_to @emptemperature, notice: 'Medición creada con exito.' }
        format.json { render :show, status: :created, location: @emptemperature }
      else
        format.html { render :new }
        format.json { render json: @emptemperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emptemperatures/1
  # PATCH/PUT /emptemperatures/1.json
  def update
    respond_to do |format|
      if @emptemperature.update(emptemperature_params)
        format.html { redirect_to @emptemperature, notice: 'Medición actualizada con exito.' }
        format.json { render :show, status: :ok, location: @emptemperature }
      else
        format.html { render :edit }
        format.json { render json: @emptemperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emptemperatures/1
  # DELETE /emptemperatures/1.json
  def destroy
    @emptemperature.destroy
    respond_to do |format|
      format.html { redirect_to emptemperatures_url, notice: 'Medición eliminada.' }
      format.json { head :no_content }
    end
  end

  def export_xlxs_employe_temperature
    @emptemperatures= Emptemperature.where(id: params[:id])
    temp = Emptemperature.where.not(id: params[:id])
    @emptemperatures += temp
    @emptemperatures.each do |emptemp|
       empt = JSON.parse(emptemp.symptoms)
       emptemp.symptoms = empt.reject(&:empty?).join(", ")
    end
    render xlsx: 'Reporte de tomas de temperatura empleados '+ Time.now.to_s, 
            template: 'reports/temperatures_employes.xlsx.axlsx'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emptemperature
      @emptemperature = Emptemperature.find(params[:id])
    end
    # Only allow a list of trusted parameters through.
    def emptemperature_params
      params.require(:emptemperature).permit(:done_by, :day_and_time, :full_name, :phone, :address, :temperature, :symptoms => [])
    end
end

app/helpers/emptemperatures_helper.rb
module EmptemperaturesHelper
	def sintomas
		['Ninguno','Fiebre','Dolor de Cabeza',
			'Tos','Dificultad para respirar',
			'Pérdida del sentido del olfato',
			'Pérdida del sentido del gusto',
			'Dolor o presión en el pecho',
			'Diarrea']
		
	end
		
end

app/views/emptemperatures/_form.html.erb
<div class="card-body">
  <%= form_with(model: emptemperature, local: true) do |form| %>
    <% if emptemperature.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(emptemperature.errors.count, "error") %> prohibited this emptemperature from being saved:</h2>

        <ul>
        <% emptemperature.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <form class="form-horizontal">
      <div class="form-group row">
        <%= form.label 'Medida por: ', class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :done_by, class:"form-control" %> 
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'Día y Hora: ', class:"col-sm-3 col-form-label"%>
         <div class="col-sm-8">
          <%= form.datetime_select :day_and_time, class:"form-control" %> 
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'Nombre Completo: ', class:"col-sm-3 col-form-label"%>
         <div class="col-sm-8">
          <%= form.text_field :full_name,class:"form-control" %> 
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'Teléfono: ', class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :phone, class:"form-control" %> 
        </div>
      </div>

      <div class="form-group row ">
        <%= form.label 'Dirección:', class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :address, class:"form-control" %> 
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'Temperatura: ', class:"col-sm-3 col-form-label"%>
        <div class="col-sm-8">
          <%= form.text_field :temperature, class:"form-control" %> 
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'Síntomas: ', class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.select :symptoms, sintomas, {}, {multiple: 'multiple', class:"col-md-9 select2bs4"} %>
        </div>
      </div>

      <div class="form-group row">
        <div class="offset-sm-2 col-sm-8">
          <%= form.submit 'Proceder', class:"btn btn-primary"%>
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-8">
          <%= link_to 'Atrás', :back , class:"btn btn-primary fa fa-arrow-left"%>
        </div>
      </div>
    </form>
    <% end %>
</div>

app/views/emptemperatures/edit.html.erb
<div class="col-md-9">
  <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <h2><%="Mediciones"%></h2>
            <div class="card card-primary">
              <div class="card-header">
                <h3><%="Creando nueva medición para empleados"%></h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                          title="Collapse">
                    <i class="fa fa-minus"></i></button>
                </div>
              </div>
                <div class="card-body">
                  <%= form_for(@emptemperature, url: {action: 'update'}, html: { method: :put, class: 'form-horizontal' }) do |form| %>
                    <% if @emptemperature.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@emptemperature.errors.count, "error") %> prohibited this emptemperature from being saved:</h2>

                        <ul>
                        <% @emptemperature.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <form class="form-horizontal">
                      <div class="form-group row">
                        <%= form.label 'Medida por: ', class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :done_by, class:"form-control" %> 
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label 'Día y Hora: ', class:"col-sm-3 col-form-label"%>
                         <div class="col-sm-8">
                          <%= form.datetime_select :day_and_time, class:"form-control" %> 
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label 'Nombre Completo: ', class:"col-sm-3 col-form-label"%>
                         <div class="col-sm-8">
                          <%= form.text_field :full_name,class:"form-control" %> 
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label 'Teléfono: ', class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :phone, class:"form-control" %> 
                        </div>
                      </div>

                      <div class="form-group row ">
                        <%= form.label 'Dirección:', class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :address, class:"form-control" %> 
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label 'Temperatura: ', class:"col-sm-3 col-form-label"%>
                        <div class="col-sm-8">
                          <%= form.text_field :temperature, class:"form-control" %> 
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label 'Síntomas: ', class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.select :symptoms, sintomas, {selected: @current_symptoms}, {multiple: 'multiple', class:"col-md-9 select2bs4"} %>
                        </div>
                      </div>

                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-8">
                          <%= form.submit 'Proceder', class:"btn btn-primary"%>
                        </div>
                      </div>
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-8">
                          <%= link_to 'Atrás', :back , class:"btn btn-primary fa fa-arrow-left"%>
                        </div>
                      </div>
                    </form>
                    <% end %>
                </div>
              </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
<!-- /.content -->
</div>

app/views/emptemperatures/index.html.erb
<div class="col-md-9" style="margin-left: 120px;">
  <!-- Content Header (Page header) -->
  <p id="notice"><%= notice %></p>
  <h1><%= 'Mediciones Empleados'%></h1>
  <div class="table-button" style="margin-bottom: 20px;margin-top: 20px; ">
    <a href="<%=temperatures_path%>" class=" btn btn-primary"><i class="fa fa-arrow-left"></i> Mediciones Usuarios</a>
  </div>
  <div class="table-button" style="margin-bottom: 20px;margin-top: 20px; ">
    <%= link_to 'Nueva medición', new_emptemperature_path, class:'btn btn-primary '%> |
    <button id="btn-rel-emptemperature" class=" btn btn-primary"><%='Recargar Tabla'%></button> | 
    <%= link_to 'Exportar Excel',export_emptemperatures_path('1') , class:'btn btn-primary '%>
  </div>
 
  <table id="emptemperatures-datatable" data-source="<%= emptemperatures_path(format: :json) %>">
    <thead>
      <tr>
        <th ><strong> Medido por </strong></th>
        <th ><strong> Día y Hora</strong></th>
        <th ><strong> Nombre Completo</strong></th>
        <th ><strong> teléfono</strong></th>
        <th ><strong> Dirección</strong></th>
        <th ><strong> Temperatura</strong></th>
        <th ><strong> Síntomas</strong></th>
        <th ><strong> Opciones</strong></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/emptemperatures/new.html.erb
<div class="col-md-9">
	<!-- Main content -->
		<section class="content">
		  <div class="container-fluid">
		    <div class="row">
		      <div class="col-md-12">
		        <h2><%="Mediciones"%></h2>
		        <div class="card card-primary">
		          <div class="card-header">
		            <h3><%="Creando nueva medición para empleados"%></h3>
		            <div class="card-tools">
		              <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
		                      title="Collapse">
		                <i class="fa fa-minus"></i></button>
		            </div>
		          </div>
		          <%= render 'form', emptemperature: @emptemperature %>
		        </div>
		        <!-- /.nav-tabs-custom -->
		      </div>
		      <!-- /.col -->
		    </div>
		    <!-- /.row -->
		  </div><!-- /.container-fluid -->
		</section>
	<!-- /.content -->
	</div>

app/views/emptemperatures/show.html.erb
<div class="col-md-9">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <h2><%='Mostrando medición'%></h2>
          <p id="notice"><%= notice %></p>
          <div class="card card-primary">
            <div class="card-header">
              <h3><%='Información medición de:'%> <%=@emptemperature.full_name%> </h3>
              <div class="card-tools">
                  <i class="fa fa-sync-alt"></i></button>
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fa fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
              <form class="form-horizontal">
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Medido por: '%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @emptemperature.done_by%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Día y Hora:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @emptemperature.day_and_time%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%='Nombre Completo:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                     <div class="form-control">
                      <%= @emptemperature.full_name %>
                    </div>  
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Teléfono:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @emptemperature.phone %>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Dirección:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @emptemperature.address%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%='Síntomas:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="">
                      <%=select_tag :symptoms, options_for_select(sintomas, selected: @current_symptoms), multiple: 'multiple', class:"col-sm-12 select2bs4", disabled: true%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%='Temperatura:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <strong><%= @emptemperature.temperature%></strong>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class="offset-sm-2 col-sm-2">
                    <%= link_to 'Atrás', :back , class:"btn btn-primary fa fa-arrow-left"%>
                  </div>
                  <div class="offset-sm-2 col-sm-2">
                    <%=link_to 'Mediciones empleados', emptemperatures_path(),class:"btn btn-primary fa fa-thermometer"%>
                  </div>
                </div>
              </form>
            </div><!-- /.card-body -->
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>