config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :emptemperatures do 
    get '/emptemperatures.xls', to: 'emptemperatures#export_xlxs_employe_temperature', as: 'export', on: :collection
  end
  resources :temperatures do
   get '/temperatures.xls', to: 'temperatures#export_xlxs', as: 'export' , on: :collection
  end
  resources :languages do
      get '/change_language', to: 'languages#change_language', as: 'change_language', on: :collection

      get '/current_language', to: 'languages#current_language', as: 'c_language', on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/temperature.rb
class Temperature < ApplicationRecord
	
end

app/controllers/temperatures_controller.rb
class TemperaturesController < ApplicationController
  before_action :set_temperature, only: [:show, :edit, :update, :destroy]

  # GET /temperatures
  # GET /temperatures.json
 
  def index
    @temperatures = Temperature.all
    respond_to do |format|
      format.html
      format.json {render json: TemperatureDatatable.new(params,{edit: edit_temperature_path('_'), show: temperature_path('_')})}
    end
  end

  # GET /temperatures/1
  # GET /temperatures/1.json
  def show
    @current_status = JSON.parse(@temperature.status)
  end

  # GET /temperatures/new
  def new
    @temperature = Temperature.new
  end

  # GET /temperatures/1/edit
  def edit
    @current_status = JSON.parse(@temperature.status)
  end

  # POST /temperatures
  # POST /temperatures.json
  def create
    @temperature = Temperature.new(temperature_params)

    respond_to do |format|
      if @temperature.save
        format.html { redirect_to @temperature, notice: 'Medición creada con exito.' }
        format.json { render :show, status: :created, location: @temperature }
      else
        format.html { render :new }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /temperatures/1
  # PATCH/PUT /temperatures/1.json
  def update
    respond_to do |format|
      if @temperature.update(temperature_params)
        format.html { redirect_to @temperature, notice: 'Medición actualizada.' }
        format.json { render :show, status: :ok, location: @temperature }
      else
        format.html { render :edit }
        format.json { render json: @temperature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /temperatures/1
  # DELETE /temperatures/1.json
  def destroy
    @temperature.destroy
    respond_to do |format|
      format.html { redirect_to temperatures_url, notice: 'Medición eliminada con exito.' }
      format.json { head :no_content }
    end
  end

  def export_xlxs
    @temperature = Temperature.where(id: params[:id])
    temp = Temperature.where.not(id: params[:id])
    @temperature += temp
    render xlsx: 'Reporte de tomas de temperatura usuarios '+ Time.now.to_s, 
            template: 'reports/temperatures_list.xlsx.axlsx'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_temperature
      @temperature = Temperature.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def temperature_params
      params.require(:temperature).permit(:checked_by, :full_name, :checked_at, :address, :phone, :temperature, :status =>[])
    end
end

app/helpers/temperatures_helper.rb
module TemperaturesHelper
	def estado
		['Normal','Fiebre','Dolor de Cabeza',
			'Tos','Dificultad para respirar',
			'Pérdida del sentido del olfato',
			'Pérdida del sentido del gusto',
			'Dolor o presión en el pecho',
			'Diarrea']
		
	end
end

app/views/temperatures/_form.html.erb
<div class="card-body">
  <%= form_with(model: temperature, local: true) do |form| %>
    <% if temperature.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(temperature.errors.count, "error") %> prohibited this temperature from being saved:</h2>

        <ul>
        <% temperature.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <form class="form-horizontal">
      <div class="form-group row">
        <%= form.label " Medido por: ", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :checked_by, class:"form-control"%>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label "Nombre Completo: ", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :full_name, class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label "Dirección: ", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :address, class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label "Teléfono: ", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.text_field :phone, class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label "Temperatura: ", class:"col-sm-3 col-form-label"  %>
        <div class="col-sm-8">
          <%= form.text_field :temperature, class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label 'Estado: ', class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.select :status, estado, {}, {multiple: 'multiple', class:"col-md-9 select2bs4"} %>
        </div>
      </div>

       <div class="form-group row">
        <%= form.label "Dia de Medición:", class:"col-sm-3 col-form-label" %>
        <div class="col-sm-8">
          <%= form.datetime_select :checked_at, class:"form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-8">
          <%= form.submit 'Proceder', class:"btn btn-primary"%>
        </div>
      </div>
      <div class="form-group row">
        <div class="offset-sm-2 col-sm-8">
          <%= link_to 'Atrás', :back , class:"btn btn-primary fa fa-arrow-left"%>
        </div>
      </div>
    </form>
  <% end %>
</div>

app/views/temperatures/edit.html.erb
<div class="col-md-9">
  <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <h2><%="Mediciones"%></h2>
            <div class="card card-primary">
              <div class="card-header">
                <h3><%="Creando nueva medición para suscriptores"%></h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                          title="Collapse">
                    <i class="fa fa-minus"></i></button>
                </div>
              </div>
                <div class="card-body">
                  <%= form_for(@temperature, url:{action: 'update'}, html: { method: :put, class: 'form-horizontal' }) do |form| %>
                    <% if @temperature.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@temperature.errors.count, "error") %> prohibited this temperature from being saved:</h2>

                        <ul>
                        <% @temperature.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                        <% end %>
                        </ul>
                      </div>
                    <% end %>
                    <form class="form-horizontal">
                      <div class="form-group row">
                        <%= form.label " Medido por: ", class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :checked_by, class:"form-control"%>
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label "Nombre Completo: ", class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :full_name, class:"form-control" %>
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label "Dirección: ", class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :address, class:"form-control" %>
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label "Teléfono: ", class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :phone, class:"form-control" %>
                        </div>
                      </div>

                      <div class="form-group row">
                        <%= form.label "Temperatura: ", class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.text_field :temperature, class:"form-control" %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <%= form.label 'Estado: ', class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.select :symptoms,estado, {selected: @current_status}, {multiple: 'multiple', class:"col-md-9 select2bs4"} %>
                        </div>
                      </div>

                       <div class="form-group row">
                        <%= form.label "Dia de Medición:", class:"col-sm-3 col-form-label" %>
                        <div class="col-sm-8">
                          <%= form.datetime_select :checked_at, class:"form-control" %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-8">
                          <%= form.submit 'Proceder', class:"btn btn-primary"%>
                        </div>
                      </div>
                      <div class="form-group row">
                        <div class="offset-sm-2 col-sm-8">
                          <%= link_to 'Atrás', :back , class:"btn btn-primary fa fa-arrow-left"%>
                        </div>
                      </div>
                    </form>
                  <% end %>
                </div>
              </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
<!-- /.content -->
</div>

app/views/temperatures/index.html.erb
<div class="col-md-9" style="margin-left: 120px;">
  <!-- Content Header (Page header) -->
  <p id="notice"><%= notice %></p>
  <h1><%= 'Mediciones Usuarios'%></h1>
   <div class="table-button" style="margin-bottom: 20px;margin-top: 20px; ">
    <a href="<%=emptemperatures_path%>" class=" btn btn-primary"><i class="fa fa-arrow-left"></i> Mediciones empleados</a>
  </div>
  <div class="table-button" style="margin-bottom: 20px;margin-top: 20px; ">
    <%= link_to 'Nueva medición', new_temperature_path, class:'btn btn-primary '%> |
    <button id="btn-rel-temperature" class=" btn btn-primary"><%='Recargar Tabla'%></button> | 
    <%= link_to 'Exportar Excel',export_temperatures_path('1') , class:'btn btn-primary '%>
  </div>
 
  <table id="temperatures-datatable" data-source="<%= temperatures_path(format: :json) %>">
    <thead>
      <tr>
        <th ><strong> Medido por </strong></th>
        <th ><strong> Nombre completo</strong></th>
        <th ><strong> Dirección</strong></th>
        <th ><strong> teléfono</strong></th>
        <th ><strong> Temperatura</strong></th>
        <th ><strong> Estado</strong></th>
        <th ><strong> Día de Medición</strong></th>
        <th ><strong> Opciones</strong></th>
      </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>



app/views/temperatures/new.html.erb
<div class="col-md-9">
<!-- Main content -->
	<section class="content">
	  <div class="container-fluid">
	    <div class="row">
	      <div class="col-md-12">
	        <h2><%="Mediciones"%></h2>
	        <div class="card card-primary">
	          <div class="card-header">
	            <h3><%="Creando nueva medición para usuarios"%></h3>
	            <div class="card-tools">
	              <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
	                      title="Collapse">
	                <i class="fa fa-minus"></i></button>
	            </div>
	          </div>
	          <%= render 'form', temperature: @temperature %>
	        </div>
	        <!-- /.nav-tabs-custom -->
	      </div>
	      <!-- /.col -->
	    </div>
	    <!-- /.row -->
	  </div><!-- /.container-fluid -->
	</section>
<!-- /.content -->
</div>

app/views/temperatures/show.html.erb
<div class="col-md-9">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <h2><%='Mostrando medición'%></h2>
          <p id="notice"><%= notice %></p>
          <div class="card card-primary">
            <div class="card-header">
              <h3><%='Información medición de:'%> <%=@temperature.full_name%> </h3>
              <div class="card-tools">
                  <i class="fa fa-sync-alt"></i></button>
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fa fa-minus"></i></button>
              </div>
            </div>
            <div class="card-body">
              <form class="form-horizontal">
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Medido por: '%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @temperature.checked_by%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Nombre Completo:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%=@temperature.full_name%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%='Dirección:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                     <div class="form-control">
                      <%=  @temperature.address %>
                    </div>  
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Teléfono:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @temperature.phone %>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%= 'Temperatura:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <%= @temperature.temperature%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%='Estado:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="">
                      <%=select_tag :symptoms, options_for_select(estado, selected: @current_status), multiple: 'multiple', class:"col-sm-12 select2bs4", disabled: true%>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class= "col-sm-4 col-form-label">
                    <strong><%='Día de Medición:'%></strong>
                  </div>
                  <div class=" col-sm-7">
                    <div class="form-control">
                      <strong><%= @temperature.checked_at%></strong>
                    </div> 
                  </div>
                </div>
                <div class="form-group row">
                  <div class="offset-sm-2 col-sm-2">
                    <%= link_to 'Atrás', :back , class:"btn btn-primary fa fa-arrow-left"%>
                  </div>
                  <div class="offset-sm-2 col-sm-2">
                    <%=link_to 'Mediciones suscriptores', temperatures_path(),class:"btn btn-primary fa fa-thermometer"%>
                  </div>
                </div>
              </form>
            </div><!-- /.card-body -->
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
</div>