config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :emptemperatures do 
    get '/emptemperatures.xls', to: 'emptemperatures#export_xlxs_employe_temperature', as: 'export', on: :collection
  end
  resources :temperatures do
   get '/temperatures.xls', to: 'temperatures#export_xlxs', as: 'export' , on: :collection
  end
  resources :languages do
      get '/change_language', to: 'languages#change_language', as: 'change_language', on: :collection

      get '/current_language', to: 'languages#current_language', as: 'c_language', on: :collection
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/layouts/partials/_language_switcher.html.erb
<div class="dropdown pull-left" id="links-languages">
  <button aria-expanded="true" aria-haspopup="true" class="btn btn-default" data-toggle="dropdown" id="dropdownLanguage" type="button" data-abbr="<%= I18n.locale.to_s %>">Cambiar Idioma
    <span class="flag-icon flag-icon-<%= I18n.locale.to_s %>"></span>
    <span class="caret"></span>
  </button>
  <ul aria-labelledby="dropdownLanguage" class="dropdown-menu btn btn-default">
    <% Language.where.not(abbreviation: I18n.locale.to_s).each do |language| %>
      <li>
        <a class="change_language" data-abbr="<%= language.abbreviation %>" data-url="<%= change_language_languages_path %>">
          <span class="flag-icon flag-icon-<%= language.abbreviation %>"></span>
          <span>
            <%= language.description %>
          </span>
        </a>
      </li>
    <% end %>
  </ul>
</div>